### ISSUE TITLE
phasecal-target loop implementation

### ISSUE THREAD

**Issue by rdeane** [ratt-ru/simms#43]
Before implementing this manually, I thought I'd ask those involved with simms if they have thought about simulating phase-target loops. I know of the scan lag option, but this won't really work (or offer sufficient flexibility) for the application of generating a realistic observing schedule, where we have a nodding between phasecal and target with some duty cycle and the associated slew-time gaps.

**Comment by SpheMakh** [comment]
I think the workaround is to simulate multiple MSs then combine them with CASA virtualconcat/concat for further processing. We doing the same in the MeerKATHI pipeline when we have multiple files for a given observation, or using calibrator field from different observation. 

But will try to implement this scenario in simms.

**Comment by rdeane** [comment]
Indeed, that was my workaround too. Surprisingly it even works for VLBI MSs :)

**Comment by SpheMakh** [comment]
This is now possible in one line! Here is an example: 

```
simms -T kat-7 -date UTC,2014/05/26/12:12:12 -dt 10 -st 4 -sl 1 -sl 0.167 -sl 0.1 -f0 1.4GHz -nc 10 -dir J2000,0deg,-30deg -dir J2000,0deg,-40deg 
```

This will observer the first field (J2000,0deg,-30deg) for 1 hour, then the second field (J2000,0deg,-40deg) for 0.167 hours (10 minutes) and repeat until 4 hours is reached.

**Comment by bennahugo** [comment]
Stale. Closing
