### ISSUE TITLE
CASA not initialised properly 

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/simms#59]
```bash
  File "/home/adas/miniconda3/envs/rapid/lib/python3.9/site-packages/simms-1.2.1-py3.9.egg/simms/casasm.py", line 103, in makems
    obs_pos = obs_pos or me.observatory(tel)
NameError: name 'me' is not defined 
```

**Comment by joshua-benabou** [comment]
Hello,

I have encountered the same bug. It looks like `me ` refers to the measures class of CASA, tried looking through previous commits to see where it might have been defined, but did not find anything...

I appreciate your help in getting this working!

**Comment by SpheMakh** [comment]
Hi @joshua-benabou, I will push a fix in a couple of days.

**Comment by joshua-benabou** [comment]
thanks @SpheMakh really looking forward to that!

**Comment by joshua-benabou** [comment]
hey @SpheMakh any luck on this?
